### ISSUE TITLE
Cannot find module 'end-of-stream'

### ISSUE THREAD

**Issue by ivanceras** [ianwalter/ng-boilerplate#18]
I get this error when issuing gulp
I already did 
`sudo npm install bower -g`
`sudo npm install gulp -g`
`bower install`

```bash
~/playground/ng-boilerplate$ gulp

module.js:340
    throw err;
          ^
Error: Cannot find module 'end-of-stream'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/test/playground/ng-boilerplate/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:5:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

What am i missing?

**Comment by crypticmind** [comment]
I fixed this by running ```npm install gulp```

**Comment by juanvillegas** [comment]
same here
